name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tests
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        
      - name: Start the app
        run: |
          npm start &
          sleep 5
      # The '&' runs the command in the background, allowing the next step to run without waiting for it to finish.
      
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          project: ./portfolio_and_tests
          browser: chrome
