name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tests
        uses: actions/checkout@v3
        with:
            repository: BilVaD1/MyPortfolio
            path: portfolio_and_tests # This is the path to the folder on the virtual machine to the folder with main branch
            ref: Tests # Name of repository

      - name: Install dependencies
        run: |
          cd portfolio_and_tests
          npm install
        
      - name: Start the app
        run: |
          npm start &
          sleep 5
      # The '&' runs the command in the background, allowing the next step to run without waiting for it to finish.
      
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          project: ./portfolio_and_tests
          browser: chrome
